# Generated by Django 4.2.16 on 2025-04-27 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length (feet)')),
                ('breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Breadth (feet)')),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Land Area (sq ft)')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20)),
                ('stage_type', models.CharField(choices=[('ceiling', 'Ceiling'), ('flooring', 'Flooring'), ('plumbing', 'Plumbing'), ('painting', 'Painting'), ('foundation', 'Foundation'), ('framing', 'Framing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('roofing', 'Roofing'), ('drywall', 'Drywall'), ('insulation', 'Insulation'), ('siding', 'Siding'), ('windows', 'Windows'), ('doors', 'Doors'), ('landscaping', 'Landscaping'), ('finishing', 'Finishing'), ('furniture_installation', 'Furniture Installation'), ('final_touchups', 'Final Touch-ups')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projectsite.project')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Spent')),
                ('date', models.DateField(verbose_name='Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projectsite.project', verbose_name='Project')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectsite.stage', verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['date'],
            },
        ),
    ]
