# Generated by Django 4.2.20 on 2025-04-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0002_remove_expense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_duration',
        ),
    ]
