# Generated by Django 4.2.16 on 2025-05-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontsite', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
