# Generated by Django 4.2.20 on 2025-04-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
