# Generated by Django 4.2.20 on 2025-04-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
